apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq-receiver
  name: rabbitmq-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-receiver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbitmq-receiver
    spec:
      containers:
      - image: localhost:5000/rabbitmq-receiver
        name: rabbitmq-receiver
        env:
        - name: RMQ_USERNAME
          value: rmquser
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        - name: RMQ_QUEUE
          value: hello
        resources: {}
status: {}
